version: '3'

services:
  app:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env.docker
    ports:
      - "8000:8000"
    expose:
      - "8000"
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: celery -A app worker -l info -B
    env_file:
      - ./.env.docker
    depends_on:
      - app
      - redis
